name: tutorial
description: New project with educational purpose.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  path_provider: ^2.0.11
  sizer: ^2.0.15
  flutter_svg: ^1.1.5
  dart_code_viewer2: ^1.0.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf

    # FaNum fonts
    - family: YekanBakhFaNumHairline
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_01_Hairline.ttf
    - family: YekanBakhFaNumThin
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_02_Thin.ttf
    - family: YekanBakhFaNumLight
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_03_Light.ttf
    - family: YekanBakhFaNumRegular
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_04_Regular.ttf
    - family: YekanBakhFaNumMedium
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_05_Medium.ttf
    - family: YekanBakhFaNumBold
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_06_Bold.ttf
    - family: YekanBakhFaNumHeavy
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_07_Heavy.ttf
    - family: YekanBakhFaNumFat
      fonts:
        - asset: fonts/Yekan_Bakh_FaNum_08_Fat.ttf